spring:
  config:
    import: nacos:${spring.application.name}-dev.yaml
  cloud:
    nacos:
      discovery:
        server-addr: 38.76.188.242:8848
        namespace: dev-luan
        username: nacos
        password: ${NACOS_PASSWORD}
      config:
        server-addr: 38.76.188.242:8848
        namespace: dev-luan
        username: nacos
        password: ${NACOS_PASSWORD}
